### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by xsro** [xsro/masm-tasm#11]
- [ ] more friendly problem information display: translation, macro 
- [ ] support multi-file assembly

#### Hover

- [ ] offer port address description, interrupt command description
- [ ] collect ASM keyword information in [scripts/keyword.json](https://github.com/xsro/masm-tasm/blob/next/scripts/keyword.json), make the hover contains more correct information

#### Symbol
- [ ] offer the rename feature

## About basic Assembly Language Features

- [ ] improve language configurations and syntax, 

## About Interaction with DOSBox and msdos-player

- [ ]  offer some ways for users to use their command to compile the codes
- [ ] download the package of dosbox according to the system
